### ISSUE TITLE
Code looks neat and clean . Infact i myself learnt many things . Well done . Just some points to ask

### ISSUE THREAD

**Issue by Nish-Hub** [ity-mehta/Covid-Service#1]
1. The traffic still would be managed in your controller because i dont see async request handler? 
2.  There are two ways of including mongo repo , Spring Data's MongoTemplate or MongoRepository. Why did we go with MongoRepo ?
3. The model TravelHistory looks well but just to ask, how do u propose a plan where in if i increase the json objects in the data coming from url , the api must be atleast smart enough to understand there the json objects have increased and hence it needs to persist them in mongo too along with the other objects ?
4. Liked the use of Interface in service package . 
5. What way do u propose to prepare this API for production release where this data size is having millions of json object record in the url and the frontend this backend is getting integrated to has around 1000 requests / sec

**Comment by ity-mehta** [comment]
Added async request handler
